### PR TITLE
wt88047: Add back libcneapiclient

### PR DESCRIPTION
**Pull request by niclimcy**
* Required by netmgrd

### CODE REVIEW

**Comment by NeoDarkness** [comment]
@ciwrl @Tortel @TheMuppets

**Comment by NeoDarkness** [comment]
@fourkbomb @invisiblek

**Comment by NeoDarkness** [comment]
@luca020400 please merge this

**Comment by invisiblek** [comment]
if i get another fucking email for this i'm taking it off nightlies. fucking stop it.

**Pull request merged**
