### PR TITLE
wt88047: Fix dark video capture

### PR DESCRIPTION
**Pull request by kenymccornick**
There is an issue with some of the stock libchromatix libraries (specifically the ov2680 and the ov8865_q8v18a) that causes video capture to be extremely dark under good light conditions. This commit fixes it by replacing those faulty libraries with the ones that work as expected (ov2680_5987fhq and ov8865_sunny).

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by danielstuart14** [comment]
@kumajaya

**Comment by kumajaya** [comment]
@ciwrl I don't like this patch commit message format (too long) but the patch itself confirmed works. Please merge.

**Comment by kenymccornick** [comment]
@kumajaya, noted. I'll keep it short in the future, thanks!

**Comment by kumajaya** [comment]
@ciwrl @intervigilium @cyanogen or anyone else that have write access here, please...

**Comment by niclimcy** [comment]
@kumajaya I think you might need to cherry-pick to your own repo so that @TheMuppets will pull from your repo

**Comment by kumajaya** [comment]
Please abandon this request. Proper camera chromatix included in my last commit.

**Pull request closed without merging**
