### PR TITLE
wt88047: Regenerate proprietary blobs

### PR DESCRIPTION
**Pull request by kumajaya**
- Using new generic extract utils
- Proper camera chromatix included, thanks @NeoDarkness,
  @kenymccornick, and others
- GPS blobs from crackling, 32 bit loc_launcher from bacon

Change-Id: Ib4d888c799dca6d55d6454a6448889e9f01a27f2

### CODE REVIEW

**Comment by kumajaya** [comment]
@ciwrl  I just merged device update. Please merge this pull request. Thank you.

**Comment by kumajaya** [comment]
@ciwrl @intervigilium @cyanogen or anyone else that have write access here, please...

**Comment by Dipchikov** [comment]
Please merge this pull request. Thank you.

**Comment by kishankumar007** [comment]
@ciwrl @intervigilium @cyanogen please merge this pull request our device needs this so bad. Thank you..

**Comment by panpietrek** [comment]
@ciwrl @intervigilium @cyanogen guys, please merge this pull request ASAP. Latest CM 13 nightlies for wt88047 are pretty much unusable without these changes.

**Comment by Kimikz** [comment]
please merge, we need this so bad...

**Comment by GreenReaper** [comment]
A unofficial build using these blobs fixed my battery drain. I know you're all focused on Nougat, but it would be nice to fix this. :-)

**Pull request merged**
